---
kind: pipeline
type: exec
name: abacus checks

steps:
- name: pre commit check
  commands:
  - nix develop . --command pre-commit run --all

- name: flake check
  commands:
  - nix flake check

- name: package check
  commands:
  - nix build

- name: miri check
  commands:
  - export HOME="$(mktemp -d)"
  - nix develop . --command cargo miri setup
  - export PATH="$HOME/.cargo/bin:$PATH"
  - RUST_BACKTRACE=1 nix develop . --command cargo miri test

- name: notifiy
  commands:
  - nix run github:ambroisie/matrix-notifier
  environment:
    ADDRESS:
      from_secret: matrix_homeserver
    ROOM:
      from_secret: matrix_roomid
    USER:
      from_secret: matrix_username
    PASS:
      from_secret: matrix_password
  when:
    status:
      - failure
      - success
...
